### ISSUE TITLE
SQL. Ошибка компиляции схемы задачи (6.3. Предложение DISTINCT 3)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1591]
> При решении все время выводилась ошибка обработки. Даже при попытке обычного вывода всей таблицы выдает ошибку.

**Условие:**
Для представленной ниже схемы products напишите запрос, который выполнит выборку уникальных строк по столбцу price. В выборке должны быть отображены все столбцы, сортировка должна быть по полям name, price и count.

**Схема базы данных:**
```
CREATE TABLE products(
    id int not null primary key,
    name text,
    price int,
    count int
);
```

**Данные:**
```
INSERT INTO products VALUES(1, 'bread', 50, 10);
INSERT INTO products VALUES(2, 'milk', 75, 15);
INSERT INTO products VALUES(3, 'sugar', 105, 30);
INSERT INTO products VALUES(4, 'bread', 50, 10);
INSERT INTO products VALUES(5, 'milk', 68, 15);
INSERT INTO products VALUES(6, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
INSERT INTO products VALUES(7, 'bread', 45, 10);
INSERT INTO products VALUES(8, 'milk', 75, 15);
INSERT INTO products VALUES(9, 'sugar', 105, 30);
```

**Ваш запрос:**
`SELECT * FROM products`

**Результат:**
При обработке данных произошла ошибка. 

```
 java.sql.SQLSyntaxErrorException: unexpected token: ON
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at ru.job4j.service.SimpleSelectExecutorService.executeSelect(SqlSandboxService.kt:70)
	at ru.job4j.service.SimpleSelectExecutorService.execute(SqlSandboxService.kt:38)
	at ru.job4j.control.SqlSolutionControl.check(SqlSolutionControl.kt:66)
	at ru.job4j.control.SqlSolutionControl._init_$lambda-0(SqlSolutionControl.kt:34)
	at ru.job4j.control.Control$DefaultImpls.process(Control.kt:21)
	at ru.job4j.control.SqlSolutionControl.process(SqlSolutionControl.kt:19)
	at ru.job4j.control.Route.process(Route.kt:37)
	at ru.job4j.Main$RootHandler.handle(Main.kt:74)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1370)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:178)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hsqldb.HsqlException: unexpected token: ON
	at org.hsqldb.error.Error.parseError(Unknown Source)
	at org.hsqldb.ParserBase.unexpectedToken(Unknown Source)
	at org.hsqldb.ParserDQL.XreadSimpleValueExpressionPrimary(Unknown Source)
	at org.hsqldb.ParserDQL.XreadAllTypesValueExpressionPrimary(Unknown Source)
	at org.hsqldb.ParserDQL.XreadAllTypesPrimary(Unknown Source)
	at org.hsqldb.ParserDQL.XreadAllTypesFactor(Unknown Source)
	at org.hsqldb.ParserDQL.XreadAllTypesTerm(Unknown Source)
	at org.hsqldb.ParserDQL.XreadAllTypesCommonValueExpression(Unknown Source)
	at org.hsqldb.ParserDQL.XreadValueExpression(Unknown Source)
	at org.hsqldb.ParserDQL.XreadSelect(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQuerySpecification(Unknown Source)
	at org.hsqldb.ParserDQL.XreadSimpleTable(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryPrimary(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryTerm(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryExpressionBody(Unknown Source)
	at org.hsqldb.ParserDQL.XreadQueryExpression(Unknown Source)
	at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 35 more
```

**Comment by peterarsentev** [comment]
Поправили ошибку. У нас схема запускается через H2, а синтаксис описали PostgreSQL. 
Попробуй, если не получиться, то снова заведи ошибку.
