### ISSUE TITLE
SQL. Ошибка компиляции схемы задачи (6.1. Предложение DISTINCT 1)

### ISSUE THREAD

**Issue by DFG-ru** [peterarsentev/job4j_features_bugs#1623]
> При решении все время выводилась ошибка обработки. Даже при попытке обычного вывода всей таблицы выдает ошибку.

**Условие:**
Для представленной ниже схемы accounts напишите запрос, который вернет только уникальные записи по полю name. При этом в выборке должны быть отражены значения полей name, login, password.

**Схема базы данных:**
```
CREATE TABLE accounts(
    id int not null primary key,
    name text,
    login text,
    password text
);
```

**Данные:**
```
INSERT INTO accounts VALUES(1, 'Petr Arsentev', 'parsentev', '1234');
INSERT INTO accounts VALUES(2, 'Andrey Hincu', 'anincu', '4321');
INSERT INTO accounts VALUES(3, 'Lana Sergeeva', 'lserg', '2156');
INSERT INTO accounts VALUES(4, 'Petr Arsentev', 'arsentev_p', '1234');
INSERT INTO accounts VALUES(5, 'Andrey Hincu', 'nincu_a', '4321');
INSERT INTO accounts VALUES(6, 'Lana Sergeeva', 'serg_l', '2156');
```

**Ваш запрос:**
```
SELECT * FROM products
```

**Результат:**
При обработке данных произошла ошибка. 

```
 org.postgresql.util.PSQLException: ERROR: syntax error at or near "name"
  Position: 24
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at org.apache.commons.dbcp2.DelegatingStatement.executeQuery(DelegatingStatement.java:329)
	at ru.job4j.service.sql.SimpleSelectExecutorService.executeSelect(SqlSandboxService.kt:51)
	at ru.job4j.service.sql.SimpleSelectExecutorService.execute(SqlSandboxService.kt:29)
	at ru.job4j.control.SqlSolutionControl.check(SqlSolutionControl.kt:75)
	at ru.job4j.control.SqlSolutionControl._init_$lambda-0(SqlSolutionControl.kt:33)
	at ru.job4j.control.Control$DefaultImpls.process(Control.kt:21)
	at ru.job4j.control.SqlSolutionControl.process(SqlSolutionControl.kt:20)
	at ru.job4j.control.Route.process(Route.kt:37)
	at ru.job4j.Main$RootHandler.handle(Main.kt:74)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1370)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:178)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:562)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by AlexeyEsipov** [comment]
Изменил имя поля name на name_person
